# Fibonacci Project
# 
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
# By starting with 1 and 2, the first 10 terms will be:
# 
#              1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values 
# do not exceed four million, find the sum of the even-valued terms.


first = 1
second = 2

fibonacci = [first, second]

# Get terms
limit = 4000000
while (first + second < limit)

    fibonacci << first + second
    first = second
    second = fibonacci.last

end

puts "Fibonacci terms:"
puts fibonacci

# Get the sum of even indexes
even_index = 0;
fibonacci.length.times do |i|
    
    if(i % 2 == 0)
        even_index += fibonacci[i]
    end

end

puts ""
puts "Even Index Sum: #{even_index}"


# Get the sum of even values
even_value = 0
fibonacci.length.times do |i|

    if(fibonacci[i] % 2 == 0)
        even_value += fibonacci[i]
    end

end

puts ""
puts "Even Value Sum: #{even_value}"